#define VERSION 5
#define SPI_HOST_CTRL 0
#define DEBUG_MUX 0
#define LED_MUX 3
#define MOTOR_SELECT 0
#define MOTOR_TEST 2500
#define SERVO_OFFSET 2300
#define THROTTLE_OFFSET 341
#define THROTTLE_SCALE 47
#define AILERON_OFFSET 1024
#define AILERON_SCALE 47
#define ELEVATOR_OFFSET 1024
#define ELEVATOR_SCALE 47
#define RUDDER_OFFSET 1024
#define RUDDER_SCALE 47
#define THROTTLE_TEST 4806
#define PITCH_P 0
#define PITCH_I 0
#define PITCH_D 0
#define ROLL_P 0
#define ROLL_I 0
#define ROLL_D 0
#define YAW_P 0
#define YAW_I 0
#define YAW_D 0